name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        go: [ '1.20', '1.21' ]
    runs-on: ${{ matrix.os }}
    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: go test -v ./...
        run: go test -v ./...

  coverage:
    runs-on: 'ubuntu-latest'
    name: Coverage
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Run coverage
        run: go test -covermode=atomic -coverprofile=coverage.out -v ./...
      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov